[package]
name = "patch-testing-script"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
sp1-core = { workspace = true, features = ["neon"] }
sp1-sdk = { workspace = true }

[build-dependencies]
sp1-helper = { workspace = true }
