[workspace]
[package]
name = "aggregation-program"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
hex = "0.4.3"
sha2 = "0.10.8"
sp1-zkvm = { path = "../../../zkvm/entrypoint", features = ["verify"] }

[patch.crates-io]
sha2-v0-10-8 = { git = "https://github.com/sp1-patches/RustCrypto-hashes.git", package = "sha2", branch = "patch-v0.10.8" }
