name: Evaluate Performance

on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC every day

jobs:
  benchmark:
    name: Benchmark
    runs-on: ${{ matrix.runner_label }}
    strategy:
      matrix:
        include:
          - runner_label: self-hosted-x86
            arch: x86
          - runner_label: self-hosted-arm64
            arch: arm64
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up git private repo access
        run: |
          git config --global url."https://${{ secrets.PRIVATE_PULL_TOKEN }}@github.com/".insteadOf ssh://git@github.com
          git config --global url."https://${{ secrets.PRIVATE_PULL_TOKEN }}@github.com".insteadOf https://github.com

      - name: Setup toolchain
        id: rustc-toolchain
        run: rustup show

      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          sp1up

      - name: Build and Run Evaluation
        run: |
          ./eval.sh

      - name: Upload Benchmark as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results-${{ matrix.arch }}
          path: benchmark.csv
