name: Main

on:
  pull_request:
    branches:
      - main
    paths:
      - "cli/**"
      - "core/**"
      - "prover/**"
      - "recursion/**"
      - "derive/**"
      - "sdk/**"
      - ".github/workflows/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  plonk:
    name: Plonk Native
    runs-on:
      [
        runs-on,
        cpu=64,
        ram=256,
        family=m7i+m7a,
        hdd=80,
        image=ubuntu22-full-x64,
        spot=false,
        "run-id=${{ github.run_id }}",
      ]
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/actions/setup

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          toolchain: 1.79.0
          args: --release -p sp1-sdk --features native-gnark -- test_e2e_prove_plonk --nocapture
        env:
          RUSTFLAGS: -Copt-level=3 -Cdebug-assertions -Coverflow-checks=y -Cdebuginfo=0 -C target-cpu=native
          RUST_BACKTRACE: 1

  plonk-docker:
    name: Plonk Docker
    runs-on:
      [
        runs-on,
        cpu=64,
        ram=256,
        family=m7i+m7a,
        hdd=80,
        image=ubuntu22-full-x64,
        spot=false,
        "run-id=${{ github.run_id }}",
      ]
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/actions/setup

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          toolchain: 1.79.0
          args: --release -p sp1-sdk -- test_e2e_prove_plonk --nocapture
        env:
          RUSTFLAGS: -Copt-level=3 -Cdebug-assertions -Coverflow-checks=y -Cdebuginfo=0 -C target-cpu=native
          RUST_BACKTRACE: 1

  check-branch:
    name: Check branch
    runs-on: [ubuntu-latest, "run-id=${{ github.run_id }}"]
    steps:
      - name: Check branch
        if: github.head_ref != 'dev' && !startsWith(github.head_ref, 'release/') && !startsWith(github.head_ref, 'hotfix/')
        run: |
          echo "ERROR: You can only merge to main from dev, release/*, or hotfix/*."
          exit 1

  ssz-withdrawals:
    name: Example (SSZ Withdrawals)
    runs-on:
      [
        runs-on,
        runner=64cpu-linux-arm64,
        spot=false,
        "run-id=${{ github.run_id }}",
      ]
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/actions/setup

      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up 
          ~/.sp1/bin/cargo-prove prove --version

      - name: Install SP1 CLI
        run: |
          cd cli
          cargo install --force --locked --path .
          cd ~

      - name: Run script
        run: |
          cd examples/ssz-withdrawals/program
          cargo add sp1-zkvm --path $GITHUB_WORKSPACE/zkvm/entrypoint
          cargo prove build
          cd ../script
          cargo remove sp1-sdk
          cargo add sp1-sdk --path $GITHUB_WORKSPACE/sdk
          SP1_DEV=1 RUST_LOG=info cargo run --release

  tendermint:
    name: Example (Tendermint)
    runs-on:
      [
        runs-on,
        runner=64cpu-linux-arm64,
        spot=false,
        "run-id=${{ github.run_id }}",
      ]
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/actions/setup

      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up 
          ~/.sp1/bin/cargo-prove prove --version

      - name: Install SP1 CLI
        run: |
          cd cli
          cargo install --force --locked --path .
          cd ~

      - name: Run script
        run: |
          cd examples/tendermint/program
          cargo add sp1-zkvm --path $GITHUB_WORKSPACE/zkvm/entrypoint
          cargo prove build
          cd ../script
          cargo remove sp1-sdk
          cargo add sp1-sdk --path $GITHUB_WORKSPACE/sdk
          SP1_DEV=1 RUST_LOG=info cargo run --release
